name: Release Blazor
on:
  push:
    tags: ['blazor/v*']

jobs:
  release:
    uses: ./.github/workflows/release-package.yml
    with:
      package: blazor
      csproj-path: HerePlatform.Blazor/HerePlatform.Blazor.csproj
      test-directory: tests/HerePlatform.Blazor.Tests
      title-prefix: HerePlatform.NET.Blazor
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}
